# Tensor flow 
#### Con una forma mas directa y no tener que definir todo lo de la seccion anterior

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('iris.csv')
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0.0
1,4.9,3.0,1.4,0.2,0.0
2,4.7,3.2,1.3,0.2,0.0
3,4.6,3.1,1.5,0.2,0.0
4,5.0,3.6,1.4,0.2,0.0

Para que el estimador funcione necesita 

1-) que las columnas de las caracrteristicas no tengan espacios

2-) y que el target sean intiger

In [4]:
df.columns= ['sepal_length', 'sepal_width','petal_length','petal_width','target']
df.head()

   sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2     0.0
1           4.9          3.0           1.4          0.2     0.0
2           4.7          3.2           1.3          0.2     0.0
3           4.6          3.1           1.5          0.2     0.0
4           5.0          3.6           1.4          0.2     0.0

In [5]:
df['target'] = df['target'].apply(int)
df.head()

   sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

Ahora agarraremos las caracteristicas como X y el target como Y, como siempre lo hacemos

In [6]:
y = df['target']

In [16]:
x = df.iloc[:,:-1]

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, 
                                                    random_state=42)

In [19]:
import tensorflow as tf

Ahora crearemos las features columns

In [ ]:
# tomaoms el numerico por que todas las varaibles son numericas
feat_col = []

for col in x.columns:

    feat_col.append(tf.feature_column.numeric_column(col))

TypeError: 'module' object is not callable

### Desde aqui va el codigo actualizado que se hace para hacer lo mismo pero con tensor flow 2.X

In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import tensorflow as tf

In [23]:

# ============================
# 1. Cargar datos
# ============================
df = pd.read_csv("iris.csv")
df.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'target']

X = df.drop("target", axis=1)
y = df["target"].astype(int)   # asegurar enteros

# Train/Test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [31]:

# ============================
# 2. Definir modelo en Keras
# ============================
model = tf.keras.Sequential([
    tf.keras.layers.Dense(5, activation="relu", input_shape=(X.shape[1],)),
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dense(5, activation="relu"),
    tf.keras.layers.Dense(3, activation="softmax")  # 3 clases
])

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",  # porque y son enteros
    metrics=["accuracy"]
)

c:\Users\Erick J. Sarante\Desktop\Erick_Curso\Data_Sci_2\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

tf.keras.Sequential([...])

Crea un modelo secuencial, es decir, una pila de capas donde la salida de una es la entrada de la siguiente.

Es lo más simple de usar cuando el modelo es lineal (sin ramas ni múltiples entradas/salidas).

🔹 tf.keras.layers.Dense(10, activation="relu", input_shape=(X.shape[1],))

Capa densa (fully connected / perceptrón): cada neurona se conecta con todas las entradas.

10 → número de neuronas en esta capa.

activation="relu" → la función de activación es ReLU (Rectified Linear Unit), muy usada porque ayuda al entrenamiento profundo.

input_shape=(X.shape[1],) → forma de los datos de entrada.

X.shape[1] = número de features (en iris son 4: sepal_length, sepal_width, petal_length, petal_width).

Esto le dice a la red cuántas entradas tiene cada muestra.

In [32]:

# ============================
# 3. Entrenamiento
# ============================
history = model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=10,
    verbose=0
)

✅ model → contiene el modelo entrenado con sus pesos ajustados.

✅ history → contiene el registro de métricas y pérdidas durante el entrenamiento (sirve para análisis, gráficas de aprendizaje, etc.).

Por defecto, cuando entrenas con arrays (X_train, y_train), Keras ya hace shuffle automático en cada epoch.

Es como si internamente hiciera:

dataset = dataset.shuffle(buffer_size=len(X_train))


Entonces no necesitas poner shuffle=True explícitamente aquí, porque ya está incluido.

In [33]:

# ============================
# 4. Predicciones
# ============================
y_pred = model.predict(X_test)
final_preds = y_pred.argmax(axis=1)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step

In [34]:

# ============================
# 5. Evaluación
# ============================
print(confusion_matrix(y_test, final_preds))
print(classification_report(y_test, final_preds))

[[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45